"""Dados de materiais e paleta visual do sistema."""

MATERIAIS = [
    {"nome": "Apara Branca",    "preco": 1.00},
    {"nome": "Apara Mista",    "preco": 0.30},
    {"nome": "Bateria",  "preco": 2.00},
    {"nome": "Bloco Limpo",    "preco": 6.00},
    {"nome": "Bloco Misto", "preco": 4.00},
    {"nome": "Bloco Sujo", "preco": 2.00},
    {"nome": "Cavaco Alum", "preco": 1.50},
    {"nome": "Chaparia", "preco": 5.00},
    {"nome": "Chumbo duro",    "preco": 2.50},
    {"nome": "Chumbo mole",    "preco": 3.00},
    {"nome": "Cobre 1",  "preco": 59.00},
    {"nome": "Cobre 2",    "preco": 55.00},
    {"nome": "Cobre 4", "preco": 36.00},
    {"nome": "Eletrônico", "preco": 3.00},
    {"nome": "Ferro pesado", "preco": 0.50},
    {"nome": "Fio inst", "preco": 25.00},
    {"nome": "Fio Misto",    "preco": 10.00},
    {"nome": "Inox 304",    "preco": 2.00},
    {"nome": "Latinha",  "preco": 10.00},
    {"nome": "Litro",    "preco": 0.40},
    {"nome": "Metal", "preco": 26.00},
    {"nome": "Motor G", "preco": 18.00},
    {"nome": "Motor Kg", "preco": 2.00},
    {"nome": "Motor P", "preco": 13.00},
    {"nome": "Panela limpa",    "preco": 8.00},
    {"nome": "Papelão",    "preco": 0.40},
    {"nome": "Papel B",  "preco": 0.40},
    {"nome": "PEAD",    "preco": 1.00},
    {"nome": "Perfil", "preco": 9.00},
    {"nome": "Perfil Pintado", "preco": 7.00},
    {"nome": "Pet", "preco": 1.50},
    {"nome": "Plástico", "preco": 0.50},
    {"nome": "Plástico Ps",    "preco": 0.30},
    {"nome": "Portão",    "preco": 20.00},
    {"nome": "Portão Ferro",  "preco": 0.00},
    {"nome": "Radiador Cobre",    "preco": 15.00},
]

TEMA = {
    "fundo": "#14171a",
    "painel": "#1c2024",
    "painel_ativo": "#262c31",
    "texto": "#ece9e2",
    "muted": "#8f979e",
    "cobre": "#c9793d",
    "total": "#8fae76",
    "linha": "#33393f",
}
